name: Run-wuye999

on:
  #push:
  #  branches: main
  gollum:
  workflow_dispatch:
  schedule:
    - cron: '40 11,22 * * *'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: RUN
      run: |
        git clone -b wuye999 https://github.com/hbstarjason2021/Unicom.git ~/wuye999 && cd ~/wuye999/unicom-task/
        pip install -r requirements.txt
        #pip3 install lxml pytz requests rsa PyExecJS pycryptodomex util
        export unicom_config_1="${{ secrets.UNICOM_USER }}<<<${{ secrets.UNICOM_PASSWORD }}<<<${{ secrets.UNICOM_APPID }}<<<3<<<<<<"
        export unicom_womail_1="${{ secrets.WOMAIL_URL }}"
        python3 unicom_index.py
