name: sync-AutoSignMachine
on:
  #schedule:
  #- cron:  "1 10 * * fri"
  workflow_dispatch:
  watch:
    types: started
  #push:
  #  branches: [main]

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/simo8102/88-AutoSignMachine.git"
        source_branch: "main"
        destination_branch: "88-AutoSignMachine"
        github_token: ${{ secrets.SYNC }}
